#!/bin/bash
password=1234
count=1
if [ $user_pswd == $password ]
        then
        echo "Login Successful!"
        exit0
while [ $count -le 3 ]
do
	read -p "Enter password : " user_pwsd
	if [ $user_pswd == $password ]
	then
	echo "Login Successful!"
	exit0
