#!/bin/bash
password=1234
count=1
if [ $user_pswd == $password ]
        then
        echo "Login Successful!"
        exit0
while [ $count -le 3 ]
do
	read -p "Enter password : " user_pwsd
	if [ $user_pswd == $password ]
	then
	echo "Login Successful!"
	exit0

###########################################################################
#method 2
#!/bin/bash
password=1234
count=1
while [ $count -le 3 ]
do
read -p "Enter password : " user_pswd
	if [ $user_pswd == $password ]
        then
        echo "Login Successful!"
        exit 0
	else
	echo "Login Unsuccessful, try again "
	count=$((count+1))
	fi
done
