#!/bin/bash

read -p "Enter first number : " num1
read -p "Enter second number : " num2
greater=0
if [ $num1 == $num2 ]
then
echo "The numbers are equal"
else
	if [ $num1 -gt $num2 ]
	then
	echo "The first number $num1 is greater"
	else
	echo "The second number $num2 is greater"
	fi
fi
